In [1]:
# question 6
import numpy as np
import numpy as np
a = np.arange(1, 10)
print("Original array-")
print(a)
print("Reverse array-")
a = a[::-1]
print(a)

Original array-
[1 2 3 4 5 6 7 8 9]
Reverse array-
[9 8 7 6 5 4 3 2 1]


In [3]:
# question 7
import numpy as np
a =  np.arange(0, 9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
# quesion 8
import numpy as np
identitymatrix=np.identity(3)
print('3x3 Identity Matrix:')
print(identitymatrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
# question 9
import numpy as np
Z = np.random.random((10,11))
a = np.amax(Z, axis=0)


print(a)

[0.94785463 0.9975572  0.99491531 0.94180434 0.92777734 0.95587484
 0.96478838 0.9678106  0.89926659 0.90801136 0.93116628]


In [25]:
# question 10
import numpy as np
a = np.ones((7,7))
print("Original array-")
print(a)
print("Transformed array-")
a[1:-1,1:-1] = 0
print(x)

Original array-
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
Transformed array-
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
