In [1]:
#question 11
import numpy as np
z = np.ones((5,5)) #basic array
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [2]:
#question 12
import numpy as np
z = np.random.normal(0,10,10) #random number from 0 to 10
print(z)

[  2.63859331  -1.46278202  26.48448005 -10.07589027   6.26658897
  11.64026067   2.51010375   4.98342817   1.10490323   2.18620003]


In [3]:
#question 13
import numpy as np
z = np.zeros((5,5))#basic array
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [4]:
#question 14
import numpy as np
z = np.linspace(0,1,12,endpoint=True)[1:-1] #using linspace
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [5]:
#question 15
import numpy as np
z = np.random.random(10) #basic random array
z.sort()
print("sorted array")
print(z)

sorted array
[0.02246875 0.04488778 0.12610355 0.24891795 0.28406628 0.39866609
 0.63371092 0.71653715 0.82701868 0.85072476]
